version: '3.4'
services:
  app1: &app
    hostname: app1
    build: .
    expose:
      - "8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'
  app2:
    <<: *app
    hostname: app2
    depends_on:
     - db
     - app1
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: minhasenha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
     - app1
     - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'
